print('가속도(m/s²) = ',end='')
a=input()
print('처음 속도(m/s) = ',end='')
v0=input()
print('나중 속도(m/s) = ',end='')
v=input()
print('시간(s) = ',end='')
t=input()
print('거리(m) = ',end='')
s=input()
print('질량(kg) = ',end='')
m=input()
print('알짜힘(N) = ',end='')
F=input()
print()
print('알고 싶은것은? : ',end='')
answer=input()
while(answer=='끝'or answer=='없음'):
    